# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3367c4c0a54f1c88e894cb95a788bd2f295b8ed7fb00101f181cc9af16c73311616199f66e55ab36b21e2559bb1b479271d80f9973618a2edbae16f34ab3c243

test:
  secret_key_base: fd01bc414c9a580f48a0d0d84446030e1bfb6b8febfdd6932372e154e4ca9e661c2e390aaeba0a5083737c4a1a474322df61e02601241e673a19b2d15c490a9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
